export const allModuleList = [
  "Dashboard",
  "Farms",
  "Devices",
  "Tractors",
  "Attachments",
  "Store",
  "Storetractors",
  "Category",
  "Services",
  "Bookings",
  "Lease",
  "Subscriptions",
  "Inquiry",
  "Statements",
  "Payment History",
  "Payment Methods",
  "Accounting",
  "Currency",
  "Package",
  "Coupon",
  "Purchase",
  "Owner",
  "Farmers",
  "Agents",
  "Dealers",
  "Operators",
  "Admins",
  "Roles",
  "Permissions",
  "Country",
  "City",
  "Logs",
  "Affiliation",
  "Insurance",
  "Investors",
  "Loans",
];