const subcontinentRegions: { [key: string]: string[] } = {
    SouthAsia: [
      "India",
      "Pakistan",
      "Bangladesh",
      "Nepal",
      "Bhutan",
      "Sri Lanka",
      "Maldives",
    ],
    EastAsia: [
      "China",
      "Japan",
      "Mongolia",
      "North Korea",
      "South Korea",
      "Taiwan",
    ],
    SoutheastAsia: [
      "Brunei",
      "Cambodia",
      "Indonesia",
      "Laos",
      "Malaysia",
      "Myanmar",
      "Philippines",
      "Singapore",
      "Thailand",
      "Timor-Leste",
      "Vietnam",
    ],
    CentralAsia: [
      "Kazakhstan",
      "Kyrgyzstan",
      "Tajikistan",
      "Turkmenistan",
      "Uzbekistan",
    ],
    WesternAsia: [
      "Armenia",
      "Azerbaijan",
      "Bahrain",
      "Cyprus",
      "Georgia",
      "Iraq",
      "Israel",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Oman",
      "Palestine",
      "Qatar",
      "Saudi Arabia",
      "Syria",
      "Turkey",
      "United Arab Emirates",
      "Yemen",
    ],
    NorthernEurope: [
      "Denmark",
      "Estonia",
      "Finland",
      "Iceland",
      "Ireland",
      "Latvia",
      "Lithuania",
      "Norway",
      "Sweden",
      "United Kingdom",
    ],
    SouthernEurope: [
      "Albania",
      "Andorra",
      "Bosnia and Herzegovina",
      "Croatia",
      "Greece",
      "Italy",
      "Malta",
      "Montenegro",
      "North Macedonia",
      "Portugal",
      "San Marino",
      "Serbia",
      "Slovenia",
      "Spain",
      "Vatican City",
    ],
    EasternEurope: [
      "Belarus",
      "Bulgaria",
      "Czech Republic",
      "Hungary",
      "Poland",
      "Moldova",
      "Romania",
      "Russia",
      "Slovakia",
      "Ukraine",
    ],
    WesternEurope: [
      "Austria",
      "Belgium",
      "France",
      "Germany",
      "Liechtenstein",
      "Luxembourg",
      "Monaco",
      "Netherlands",
      "Switzerland",
    ],
    NorthernAfrica: [
      "Algeria",
      "Egypt",
      "Libya",
      "Morocco",
      "Sudan",
      "Tunisia",
      "Western Sahara",
    ],
    WesternAfrica: [
      "Benin",
      "Burkina Faso",
      "Cape Verde",
      "Côte d'Ivoire",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Mauritania",
      "Niger",
      "Nigeria",
      "Senegal",
      "Sierra Leone",
      "Togo",
    ],
    CentralAfrica: [
      "Angola",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Congo (Brazzaville)",
      "Congo (Kinshasa)",
      "Equatorial Guinea",
      "Gabon",
      "São Tomé and Príncipe",
    ],
    EasternAfrica: [
      "Burundi",
      "Comoros",
      "Djibouti",
      "Eritrea",
      "Ethiopia",
      "Kenya",
      "Madagascar",
      "Malawi",
      "Mauritius",
      "Mozambique",
      "Rwanda",
      "Seychelles",
      "Somalia",
      "South Sudan",
      "Tanzania",
      "Uganda",
      "Zambia",
      "Zimbabwe",
    ],
    SouthernAfrica: [
      "Botswana",
      "Eswatini",
      "Lesotho",
      "Namibia",
      "South Africa",
    ],
    CentralAmerica: [
      "Belize",
      "Costa Rica",
      "El Salvador",
      "Guatemala",
      "Honduras",
      "Nicaragua",
      "Panama",
    ],
    Caribbean: [
      "Antigua and Barbuda",
      "Bahamas",
      "Barbados",
      "Cuba",
      "Dominica",
      "Dominican Republic",
      "Grenada",
      "Haiti",
      "Jamaica",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Trinidad and Tobago",
    ],
    SouthAmerica: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
    NorthernAmerica: [
      "Canada",
      "United States",
      "Mexico",
    ],
    Oceania: [
      "Australia",
      "Fiji",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "New Zealand",
      "Palau",
      "Papua New Guinea",
      "Samoa",
      "Solomon Islands",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
    ],
    AntarcticRegion: [
      "Antarctica",
    ],
  };
  
  export default subcontinentRegions;